### ISSUE TITLE
Is there a reason you didn't add the "Person" label?

### ISSUE THREAD

**Issue by newrachael** [john-rocky/easyportrait-coreml#1]
Firstly, thank you for your research. I'm raising an issue because I have a question.
The "Person" label is present in the original project, but it seems to be missing in yours. 

Do you have any idea if there is any particular reason for this?

**Comment by john-rocky** [comment]
This is because the person label outputs a completely black image in the face-parsing task.
Perhaps this label should be used for the person-segmentation model?

**Comment by newrachael** [comment]
Ah, so that was the problem, thanks for the reply. 

I came across your code while working on segmenting a human head and was checking it out.  Thanks.
